---
title: "Visualize sound as a spectrogram"
output: NULL
---

```{r}
packages <- c("seewave", "tuneR", "viridis", "grid", "gridExtra", "tidyverse")
if(!require("pacman", character.only = TRUE)) install.packages("pacman")
pacman::p_load(char = packages)
```

```{r set themes}
# code from Joshua Flickinger @ http://rug.mnhn.fr/seewave/spec.html

# x label formatter
s_formatter <- function(x){
  lab <- paste0(x, " s")
}

# y label formatter
khz_formatter <- function(y){
  lab <- paste0(y, " kHz")
}

# set themes
oscillo_theme_dark <- theme(panel.grid.major.y = element_line(color="black", linetype = "dotted"),
                            panel.grid.major.x = element_blank(),
                            panel.grid.minor = element_blank(),
                            panel.background = element_rect(fill="transparent"),
                            panel.border = element_rect(linetype = "solid", fill = NA, color = "grey"),
                            axis.line = element_blank(),
                            legend.position = "none",
                            plot.background = element_rect(fill="black"),
                            plot.margin = unit(c(0,1,1,1), "lines"),
                            axis.title = element_blank(),
                            axis.text = element_text(size=10, color = "grey"),
                            axis.ticks = element_line(color="grey"))

hot_theme <- theme(panel.grid.major.y = element_line(color="black", linetype = "dotted"),
                   panel.grid.major.x = element_blank(),
                   panel.grid.minor = element_blank(),
                   panel.background = element_rect(fill="transparent"),
                   panel.border = element_rect(linetype = "solid", fill = NA, color = "grey"),
                   axis.line = element_blank(),
                   legend.position = "top",
                   legend.justification = "right",
                   legend.background = element_rect(fill="black"),
                   legend.key.width = unit(50, "native"),
                   legend.title = element_text(size=12, color="grey"),
                   legend.text = element_text(size=12, color="grey"),
                   plot.background = element_rect(fill="black"),
                   axis.title = element_blank(),
                   axis.text = element_text(size=12, color = "grey"),
                   axis.ticks = element_line(color="grey"))

hot_theme_grid <- theme(panel.grid.major.y = element_line(color="black", linetype = "dotted"),
                        panel.grid.major.x = element_blank(),
                        panel.grid.minor = element_blank(),
                        panel.background = element_rect(fill="transparent"),
                        panel.border = element_rect(linetype = "solid", fill = NA, color = "grey"),
                        axis.line = element_blank(),
                        legend.position = "top",
                        legend.justification = "right",
                        legend.background = element_rect(fill="black"),
                        legend.key.width = unit(50, "native"),
                        legend.title = element_text(size=12, color="grey"),
                        legend.text = element_text(size=12, color="grey"),
                        plot.background = element_rect(fill="black"),
                        plot.margin = margin(1,1,0,1, "lines"),
                        axis.title = element_blank(),
                        axis.text = element_text(size=12, color = "grey"),
                        axis.text.x = element_blank(),
                        axis.ticks = element_line(color="grey"))

hot_colors <- inferno(n=9)
```

```{bash eval=FALSE, include=FALSE}
# brew install ffmpeg
# convert mp3 to wav
ffmpeg -i ../iTunes/iTunes\ Media/Music/Radiohead/Kid\ A/08\ Idioteque.mp3 data/Radiohead_Idioteque.wav
```

```{r load or create waveforms}
# generate waves
sine440 <- sine(440)
a_notes <- sine(440) + sine(880) + sine(1660)

# or, load from a wav file
wavefile_path <- "data/Radiohead_Idioteque.wav"
wav <- readWave(wavefile_path)

# builds a dataframe of the wave object values
sample <- seq(1:length(wav@left))
time <- sample/wav@samp.rate
sample.left <- as.vector(cbind(wav@left))
df <- data.frame(sample, time, sample.left)

# subsets the dataframe to a more manageable size for plotting
last.index <- tail(df$sample,1)
index <- seq(from = 1, to = last.index, by = 20)
df2 <- df[index,]

```

```{r build plot}
# spectrogram
spectrogram <- ggspectro(wav@left, f = wav@samp.rate) +
  geom_raster(aes(fill=amplitude), hjust = 0, vjust = 0, interpolate = F) +
  scale_x_continuous(labels=s_formatter, expand = c(0,0))+
  scale_y_continuous(breaks = seq(from = 5, to = 20, by=5), expand = c(0,0),
                     labels = khz_formatter, position = "right") +
  scale_fill_gradientn(colours = hot_colors, name = "Amplitude \n (dB)", na.value = "transparent", limits = c(-60,0)) +
  hot_theme_grid


# oscillogram
oscillogram <- ggplot(df2)+
  geom_line(mapping = aes(x=time, y=sample.left), color="grey")+ 
  scale_x_continuous(labels=s_formatter, expand = c(0,0))+
  scale_y_continuous(expand = c(0,0), position = "right")+
  geom_hline(yintercept = 0, color="white", linetype = "dotted")+
  oscillo_theme_dark

# plot grid
gA=ggplot_gtable(ggplot_build(spectrogram)) 
gB=ggplot_gtable(ggplot_build(oscillogram))
maxWidth = grid::unit.pmax(gA$widths, gB$widths)
gA$widths <- as.list(maxWidth)
gB$widths <- as.list(maxWidth)
layout <- rbind(c(1,1,1),
              c(1,1,1),
              c(1,1,1),
              c(2,2,2))

grid.newpage()
grid.arrange(gA, gB, layout_matrix = layout)

```
